### ISSUE TITLE
Refactor and update to Laravel 5.4

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-parse#5]
At this point I will do a little bit of refactoring and removing uneccessary stuff from the package.

## Tasks

- [x] Remove tests since they are not accurate and very useful.
- [x] Update the composer dependencies.
- [x] Refactor some comments and documentation in the project.
- [x] Fix error in session storage `clear` method uses `Sessions` which doesn't exist.
- [x] Rename `getAll` to `all` in session storage.
